"""Email templates for transactional emails.

Two rendering strategies are supported for each email type:

- Local templates (default): the functions below render subject/text/html
  in-process from plain Python f-strings — no external template engine
  needed. User-provided values are HTML-escaped before interpolation, and
  every HTML email is wrapped in the shared branded shell (global
  ``EMAIL_HEADER_HTML`` + content + ``EMAIL_FOOTER_HTML``) defined in
  this module.
- SendGrid Dynamic Transactional Templates: when a matching
  ``SENDGRID_*_TEMPLATE_ID`` is configured, ``user_service`` switches to
  ``email_service.send_templated_email()`` and sends only the template id
  plus a ``dynamic_template_data`` dict whose keys mirror the local
  template variables, so the same data feeds either strategy. The
  header/footer then live inside the SendGrid template itself.
"""
from datetime import date
from html import escape
from typing import Optional, Tuple


# ── Global header / footer, shared by all locally rendered emails ───────────────────────────────


# Brand dark navy — the default header background for every email.
HEADER_BG_DEFAULT = "#1a1a2e"

# Order status notifications tint the "QPMN Order Gateway" header per
# severity: info keeps the brand navy, warning renders brown, error dark
# red. Unknown levels fall back to the default.
LEVEL_HEADER_BG = {
    "info": "#0842a0",
    "warning": "#bf8e24",  # brown
    "error": "#c10d0d",    # dark red
}


def _email_header_html(bg_color: str = HEADER_BG_DEFAULT) -> str:
    return (
        "<tr>"
        f'<td style="background-color:{bg_color};padding:20px 32px;">'
        '<span style="color:#ffffff;font-size:18px;font-weight:bold;'
        'letter-spacing:0.5px;">QPMN Order Gateway</span>'
        "</td>"
        "</tr>"
    )


EMAIL_HEADER_HTML = _email_header_html()

EMAIL_FOOTER_HTML = (
    "<tr>"
    '<td style="background-color:#f8f8fa;padding:16px 32px;'
    'border-top:1px solid #eeeeee;color:#888888;font-size:12px;'
    'line-height:1.5;">'
    f"&copy; {date.today().year} @ QPMN. "
    "All rights reserved. "
    "</td>"
    "</tr>"
)


def _render_email_shell(body_html: str, header_bg: str = HEADER_BG_DEFAULT) -> str:
    """
    Wrap an email body in the branded shell: global header + content + footer.

    ``header_bg`` overrides the header background (used by order status
    notifications to tint it per level; other emails keep the brand navy).
    Uses nested tables with inline styles only — the layout technique every
    mainstream email client (Outlook, Gmail, QQ/Enterprise mail) renders
    reliably; <style> blocks and flexbox are not.
    """
    return (
        '<!DOCTYPE html>'
        '<html lang="en">'
        '<body style="margin:0;padding:0;background-color:#f4f4f7;">'
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" '
        'style="background-color:#f4f4f7;padding:24px 0;">'
        '<tr><td align="center">'
        '<table role="presentation" width="600" cellpadding="0" cellspacing="0" '
        'style="width:600px;max-width:100%;background-color:#ffffff;'
        'border-radius:8px;overflow:hidden;'
        'font-family:Arial,Helvetica,sans-serif;">'
        # ── global header ──
        f'{_email_header_html(header_bg)}'
        # ── content ──
        '<tr>'
        '<td style="padding:32px;color:#333333;font-size:14px;line-height:1.6;">'
        f'{body_html}'
        '</td>'
        '</tr>'
        # ── global footer ──
        f'{EMAIL_FOOTER_HTML}'
        '</table>'
        '</td></tr>'
        '</table>'
        '</body>'
        '</html>'
    )


# ── Password reset email ─────────────────────────────────────────


def render_password_reset_email(
    display_name: str,
    reset_link: str,
    expire_minutes: int,
    subject_prefix: str = "",
) -> Tuple[str, str, str]:
    """
    Render the password reset email.

    Returns ``(subject, text_content, html_content)``. ``display_name`` is
    escaped before going into HTML; ``reset_link`` must be a pre-built,
    URL-encoded link and is inserted verbatim (it is generated by us).
    ``subject_prefix`` lets tests mark the email (e.g. "[TEST] ").
    """
    name = escape(display_name)
    subject = f"{subject_prefix}Reset your Order Gateway password"

    text_content = (
        f"Hello {display_name},\n\n"
        f"We received a request to reset your password.\n\n"
        f"Open the link below to set a new password (valid for {expire_minutes} minutes):\n"
        f"{reset_link}\n\n"
        f"If you did not request this, you can safely ignore this email.\n"
    )
    body_html = (
        f"<p>Hello {name},</p>"
        f"<p>We received a request to reset your password.</p>"
        f"<p>Click the link below to set a new password "
        f"(valid for {expire_minutes} minutes):</p>"
        f'<p><a href="{reset_link}" '
        f'style="display:inline-block;padding:10px 24px;background-color:#4f46e5;'
        f'color:#ffffff;text-decoration:none;border-radius:4px;">Reset my password</a></p>'
        f'<p style="color:#888;font-size:12px;word-break:break-all;">{reset_link}</p>'
        f"<p>If you did not request this, you can safely ignore this email.</p>"
    )
    return subject, text_content, _render_email_shell(body_html)


def password_reset_template_data(
    display_name: str,
    reset_link: str,
    expire_minutes: int,
) -> dict:
    """
    Dynamic-template data for the SendGrid version of the reset email.

    Keys are the handlebars variables the SendGrid template must define:
    {{{display_name}}}, {{{reset_link}}}, {{{expire_minutes}}}.
    """
    return {
        "display_name": display_name,
        "reset_link": reset_link,
        "expire_minutes": expire_minutes,
    }


# ── Order status change notification email ───────────────────────


def _format_duration(seconds: int) -> str:
    """Human-friendly duration for the email's cooling-off line.

    e.g. 172800 -> "2 days", 5400 -> "1 hour 30 minutes", 45 -> "45 seconds".
    """
    minutes, sec = divmod(int(seconds), 60)
    hours, minutes = divmod(minutes, 60)
    days, hours = divmod(hours, 24)
    parts: list = []
    if days:
        parts.append(f"{days} day{'s' if days != 1 else ''}")
    if hours:
        parts.append(f"{hours} hour{'s' if hours != 1 else ''}")
    if minutes and not days:
        parts.append(f"{minutes} minute{'s' if minutes != 1 else ''}")
    if not parts:
        parts.append(f"{sec} second{'s' if sec != 1 else ''}")
    return " ".join(parts)


def render_order_status_email(
    order_id: str,
    from_status: str,
    to_status: str,
    level: str,
    message: str = "",
    source_order_id: str = "",
    store_name: str = "",
    occurred_at: str = "",
    subject_prefix: str = "",
    view_url: str = "",
    cooling_off_seconds: Optional[int] = None,
) -> Tuple[str, str, str]:
    """
    Render the order status change notification email.

    Returns ``(subject, text_content, html_content)``. The subject follows
    the "[INFO] Order {source_order_id} Received" style: it shows the
    external ``source_order_id`` (what store staff recognise, falling back
    to the internal ``order_id`` when absent) plus the target status
    title-cased (``cooling_off`` -> ``Cooling Off``). Every caller-supplied
    value is HTML-escaped before going into the HTML body; ``subject_prefix``
    lets tests mark the email (e.g. "[TEST] "); ``view_url`` (from
    ADMIN_BASE_URL, pointing at /admin/orders/show/{order_id}) renders a
    "View Details" button when non-empty, styled exactly like the password
    reset button.
    """
    level_token = escape((level or "info").upper())
    # Newly created orders enter their first status with no previous one
    # (from_status=None/"") — the body's "Status Change" row renders that
    # as "new" instead of an empty " -> received".
    from_label = from_status or "new"
    display_id = source_order_id or order_id
    to_label = (to_status or "").replace("_", " ").title()
    subject = f"{subject_prefix}[{level_token}] Order {display_id} {to_label}".rstrip()

    fields = [
        ("Order ID", order_id),
        ("Source Order ID", source_order_id),
        ("Store", store_name),
        ("Status Change", f"{from_label} -> {to_status}"),
        (
            "Cooling-off Period",
            _format_duration(cooling_off_seconds) if cooling_off_seconds else "",
        ),
        ("Level", level_token),
        ("Message", message),
        ("Occurred At (UTC)", occurred_at),
    ]

    text_content = (
        f"Order status change notification [{level_token}]\n\n"
        + "\n".join(f"{label}: {value}" for label, value in fields if value)
        + (f"\nView Details: {view_url}" if view_url else "")
        + "\n"
    )

    rows = "".join(
        f'<tr>'
        f'<td style="padding:8px 12px;border:1px solid #eeeeee;'
        f'background-color:#f8f8fa;color:#555555;width:160px;">{escape(label)}</td>'
        f'<td style="padding:8px 12px;border:1px solid #eeeeee;color:#333333;">'
        f'{escape(str(value))}</td>'
        f'</tr>'
        for label, value in fields
        if value
    )
    # Same button recipe as the password reset email: a padded block-level
    # <a> (button styling on <button>/<div> is unreliable across Outlook et
    # al), same indigo background and radius.
    button_html = ""
    if view_url:
        button_html = (
            f'<p><a href="{escape(view_url)}" '
            f'style="display:inline-block;padding:10px 24px;'
            f'background-color:#4f46e5;color:#ffffff;text-decoration:none;'
            f'border-radius:4px;">View Details</a></p>'
        )
    body_html = (
        f'<p>Order Details:</p>'
        f'<table role="presentation" cellpadding="0" cellspacing="0" width="100%" '
        f'style="border-collapse:collapse;font-size:13px;">{rows}</table>'
        f'{button_html}'
    )
    # Header tint follows the notification level (LEVEL_HEADER_BG); other
    # emails keep the brand navy default.
    header_bg = LEVEL_HEADER_BG.get((level or "info").lower(), HEADER_BG_DEFAULT)
    return subject, text_content, _render_email_shell(body_html, header_bg=header_bg)
