"""Email templates for transactional emails.

Two rendering strategies are supported for each email type:

- Local templates (default): the functions below render subject/text/html
  in-process from plain Python f-strings — no external template engine
  needed. User-provided values are HTML-escaped before interpolation, and
  every HTML email is wrapped in the shared branded shell (global
  ``EMAIL_HEADER_HTML`` + content + ``EMAIL_FOOTER_HTML``) defined in
  this module.
- SendGrid Dynamic Transactional Templates: when a matching
  ``SENDGRID_*_TEMPLATE_ID`` is configured, ``user_service`` switches to
  ``email_service.send_templated_email()`` and sends only the template id
  plus a ``dynamic_template_data`` dict whose keys mirror the local
  template variables, so the same data feeds either strategy. The
  header/footer then live inside the SendGrid template itself.
"""
from datetime import date
from html import escape
from typing import Tuple


# ── Global header / footer, shared by all locally rendered emails ───────────────────────────────


EMAIL_HEADER_HTML = (
    "<tr>"
    '<td style="background-color:#1a1a2e;padding:20px 32px;">'
    '<span style="color:#ffffff;font-size:18px;font-weight:bold;'
    'letter-spacing:0.5px;">QPMN Order Gateway</span>'
    "</td>"
    "</tr>"
)

EMAIL_FOOTER_HTML = (
    "<tr>"
    '<td style="background-color:#f8f8fa;padding:16px 32px;'
    'border-top:1px solid #eeeeee;color:#888888;font-size:12px;'
    'line-height:1.5;">'
    f"&copy; {date.today().year} @ QPMN. "
    "All rights reserved. "
    "</td>"
    "</tr>"
)


def _render_email_shell(body_html: str) -> str:
    """
    Wrap an email body in the branded shell: global header + content + footer.

    Uses nested tables with inline styles only — the layout technique every
    mainstream email client (Outlook, Gmail, QQ/Enterprise mail) renders
    reliably; <style> blocks and flexbox are not.
    """
    return (
        '<!DOCTYPE html>'
        '<html lang="en">'
        '<body style="margin:0;padding:0;background-color:#f4f4f7;">'
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" '
        'style="background-color:#f4f4f7;padding:24px 0;">'
        '<tr><td align="center">'
        '<table role="presentation" width="600" cellpadding="0" cellspacing="0" '
        'style="width:600px;max-width:100%;background-color:#ffffff;'
        'border-radius:8px;overflow:hidden;'
        'font-family:Arial,Helvetica,sans-serif;">'
        # ── global header ──
        f'{EMAIL_HEADER_HTML}'
        # ── content ──
        '<tr>'
        '<td style="padding:32px;color:#333333;font-size:14px;line-height:1.6;">'
        f'{body_html}'
        '</td>'
        '</tr>'
        # ── global footer ──
        f'{EMAIL_FOOTER_HTML}'
        '</table>'
        '</td></tr>'
        '</table>'
        '</body>'
        '</html>'
    )


# ── Password reset email ─────────────────────────────────────────


def render_password_reset_email(
    display_name: str,
    reset_link: str,
    expire_minutes: int,
    subject_prefix: str = "",
) -> Tuple[str, str, str]:
    """
    Render the password reset email.

    Returns ``(subject, text_content, html_content)``. ``display_name`` is
    escaped before going into HTML; ``reset_link`` must be a pre-built,
    URL-encoded link and is inserted verbatim (it is generated by us).
    ``subject_prefix`` lets tests mark the email (e.g. "[TEST] ").
    """
    name = escape(display_name)
    subject = f"{subject_prefix}Reset your Order Gateway password"

    text_content = (
        f"Hello {display_name},\n\n"
        f"We received a request to reset your password.\n\n"
        f"Open the link below to set a new password (valid for {expire_minutes} minutes):\n"
        f"{reset_link}\n\n"
        f"If you did not request this, you can safely ignore this email.\n"
    )
    body_html = (
        f"<p>Hello {name},</p>"
        f"<p>We received a request to reset your password.</p>"
        f"<p>Click the link below to set a new password "
        f"(valid for {expire_minutes} minutes):</p>"
        f'<p><a href="{reset_link}" '
        f'style="display:inline-block;padding:10px 24px;background-color:#4f46e5;'
        f'color:#ffffff;text-decoration:none;border-radius:4px;">Reset my password</a></p>'
        f'<p style="color:#888;font-size:12px;word-break:break-all;">{reset_link}</p>'
        f"<p>If you did not request this, you can safely ignore this email.</p>"
    )
    return subject, text_content, _render_email_shell(body_html)


def password_reset_template_data(
    display_name: str,
    reset_link: str,
    expire_minutes: int,
) -> dict:
    """
    Dynamic-template data for the SendGrid version of the reset email.

    Keys are the handlebars variables the SendGrid template must define:
    {{{display_name}}}, {{{reset_link}}}, {{{expire_minutes}}}.
    """
    return {
        "display_name": display_name,
        "reset_link": reset_link,
        "expire_minutes": expire_minutes,
    }
