sonar.projectKey=qpmn-topps-order-gateway

# Sources / tests
sonar.sources=app
sonar.tests=tests
sonar.exclusions=app/tmp/**,app/assets/**,**/__pycache__/**

# Python analyzer
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml