"""add_store_id_to_file_uploads

Revision ID: 0e51bfa74c0a
Revises: 2f9da1c3bb66
Create Date: 2026-06-23 11:16:46.357595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e51bfa74c0a'
down_revision: Union[str, Sequence[str], None] = '2f9da1c3bb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('store_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_file_uploads_store_id'), 'file_uploads', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_uploads_store_id'), table_name='file_uploads')
    op.drop_column('file_uploads', 'store_id')
    # ### end Alembic commands ###
