"""sync addresses type enum and webhook_logs columns

Revision ID: 07cb5a0806ef
Revises: a7b8c9d0e1f2
Create Date: 2026-08-11 15:45:49.195929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07cb5a0806ef'
down_revision: Union[str, Sequence[str], None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('DELIVERY', 'BILLING', name='addresstype'),
               existing_nullable=True)
    op.add_column('webhook_logs', sa.Column('headers', sa.JSON(), nullable=True))
    op.add_column('webhook_logs', sa.Column('signature_valid', sa.Boolean(), nullable=True))
    op.add_column('webhook_logs', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True))
    op.add_column('webhook_logs', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_webhook_logs_event_id'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_store_order_item_id'), table_name='webhook_logs')
    op.drop_column('webhook_logs', 'store_order_item_id')
    op.drop_column('webhook_logs', 'event_id')
    op.drop_column('webhook_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_logs', sa.Column('details', mysql.TEXT(), nullable=True))
    op.add_column('webhook_logs', sa.Column('event_id', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('webhook_logs', sa.Column('store_order_item_id', mysql.VARCHAR(length=64), nullable=True))
    op.create_index(op.f('ix_webhook_logs_store_order_item_id'), 'webhook_logs', ['store_order_item_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_event_id'), 'webhook_logs', ['event_id'], unique=False)
    op.drop_column('webhook_logs', 'processed_at')
    op.drop_column('webhook_logs', 'error_message')
    op.drop_column('webhook_logs', 'signature_valid')
    op.drop_column('webhook_logs', 'headers')
    op.alter_column('addresses', 'type',
               existing_type=sa.Enum('DELIVERY', 'BILLING', name='addresstype'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
