"""add_store_key_to_clients

Revision ID: 2f9da1c3bb66
Revises: e9f5299d3acc
Create Date: 2026-06-22 11:02:08.173516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f9da1c3bb66'
down_revision: Union[str, Sequence[str], None] = 'e9f5299d3acc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('store_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_clients_store_key'), 'clients', ['store_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_store_key'), table_name='clients')
    op.drop_column('clients', 'store_key')
    # ### end Alembic commands ###
