"""add_store_id_to_products_skus_orders

Revision ID: e9f5299d3acc
Revises: b7e2f4a91c38
Create Date: 2026-06-18 17:56:26.915548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e9f5299d3acc'
down_revision: Union[str, Sequence[str], None] = 'b7e2f4a91c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('store_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_orders_store_id'), 'orders', ['store_id'], unique=False)
    op.add_column('products', sa.Column('store_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_products_store_id'), 'products', ['store_id'], unique=False)
    op.add_column('skus', sa.Column('store_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_skus_store_id'), 'skus', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skus_store_id'), table_name='skus')
    op.drop_column('skus', 'store_id')
    op.drop_index(op.f('ix_products_store_id'), table_name='products')
    op.drop_column('products', 'store_id')
    op.drop_index(op.f('ix_orders_store_id'), table_name='orders')
    op.drop_column('orders', 'store_id')
    # ### end Alembic commands ###
